name: agora_uikit
description: Flutter plugin to simply integrate Agora Video Calling or Live Video Streaming to your app with just a few lines of code.
version: 0.0.1
homepage: https://www.agora.io/en/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^4.0.1
  http: ^0.13.1
  permission_handler: ^8.0.0+1
  lints:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_uikit
        pluginClass: AgoraUikitPlugin
      ios:
        pluginClass: AgoraUikitPlugin

analyzer:
  strong-mode: true
  errors:
    mixin_inherits_from_not_object: ignore

